import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { FetchworksClient, FetchworksError, type TranscriptItem } from "../src/index.js";

const TOKEN = "test-token";

const okItem: TranscriptItem = {
  videoId: "jNQXAC9IVRw",
  url: "https://www.youtube.com/watch?v=jNQXAC9IVRw",
  status: "ok",
  language: "en",
  isAutoGenerated: false,
  segments: [{ start: 1.3, dur: 3.4, text: "All right, so here we are" }],
  text: "All right, so here we are",
};

const noCaptionsItem: TranscriptItem = {
  videoId: "kJQP7kiw5Fk",
  url: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
  status: "no_captions",
  availableLanguages: [],
  error: "video has no caption tracks",
};

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}

let fetchMock: ReturnType<typeof vi.fn>;

beforeEach(() => {
  fetchMock = vi.fn();
  vi.stubGlobal("fetch", fetchMock);
});

afterEach(() => {
  vi.unstubAllGlobals();
  vi.useRealTimers();
});

function client(extra: Record<string, unknown> = {}): FetchworksClient {
  return new FetchworksClient({ apifyToken: TOKEN, pollIntervalMs: 1, ...extra });
}

describe("constructor", () => {
  it("requires an apifyToken", () => {
    expect(() => new FetchworksClient({} as never)).toThrow(FetchworksError);
  });
});

describe("getTranscript", () => {
  it("calls the sync endpoint with a single-video input and returns the item", async () => {
    fetchMock.mockResolvedValueOnce(jsonResponse([okItem]));

    const item = await client().getTranscript("jNQXAC9IVRw", {
      languages: ["en", "de"],
      outputFormats: ["segments", "text"],
      includeChapters: true,
    });

    expect(item).toEqual(okItem);
    expect(fetchMock).toHaveBeenCalledTimes(1);
    const [url, init] = fetchMock.mock.calls[0]!;
    expect(url).toBe(
      `https://api.apify.com/v2/acts/fetchworks~youtube-transcript-scraper/run-sync-get-dataset-items?token=${TOKEN}&clean=true`,
    );
    expect(init.method).toBe("POST");
    expect(JSON.parse(init.body)).toEqual({
      videoUrls: ["jNQXAC9IVRw"],
      languages: ["en", "de"],
      outputFormats: ["segments", "text"],
      includeChapters: true,
    });
  });

  it("passes through non-ok statuses instead of throwing", async () => {
    fetchMock.mockResolvedValueOnce(jsonResponse([noCaptionsItem]));
    const item = await client().getTranscript("kJQP7kiw5Fk");
    expect(item.status).toBe("no_captions");
    expect(item.error).toBe("video has no caption tracks");
  });

  it("throws a FetchworksError with the API message on HTTP failure", async () => {
    fetchMock.mockResolvedValueOnce(
      jsonResponse({ error: { type: "user-not-authenticated", message: "bad token" } }, 401),
    );
    await expect(client().getTranscript("jNQXAC9IVRw")).rejects.toMatchObject({
      name: "FetchworksError",
      statusCode: 401,
      message: expect.stringContaining("bad token"),
    });
  });
});

describe("getTranscripts", () => {
  it("uses the sync endpoint below 60 videos", async () => {
    const urls = Array.from({ length: 59 }, (_, i) => `video-${i}`);
    fetchMock.mockResolvedValueOnce(jsonResponse([okItem]));

    await client().getTranscripts(urls);

    expect(fetchMock).toHaveBeenCalledTimes(1);
    expect(fetchMock.mock.calls[0]![0]).toContain("run-sync-get-dataset-items");
  });

  it("uses async run + poll + dataset fetch at 60 videos or more", async () => {
    const urls = Array.from({ length: 60 }, (_, i) => `video-${i}`);
    fetchMock
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-1", status: "READY", defaultDatasetId: "ds-1" } }))
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-1", status: "RUNNING", defaultDatasetId: "ds-1" } }))
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-1", status: "SUCCEEDED", defaultDatasetId: "ds-1" } }))
      .mockResolvedValueOnce(jsonResponse([okItem, noCaptionsItem]));

    const items = await client().getTranscripts(urls);

    expect(items).toEqual([okItem, noCaptionsItem]);
    const calledUrls = fetchMock.mock.calls.map((c) => String(c[0]));
    expect(calledUrls[0]).toContain("/v2/acts/fetchworks~youtube-transcript-scraper/runs?");
    expect(calledUrls[1]).toContain("/v2/actor-runs/run-1?");
    expect(calledUrls[3]).toContain("/v2/datasets/ds-1/items?");
  });

  it("paginates the dataset when a page comes back full", async () => {
    const bigPage = Array.from({ length: 1000 }, () => okItem);
    fetchMock
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-1", status: "READY", defaultDatasetId: "ds-1" } }))
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-1", status: "SUCCEEDED", defaultDatasetId: "ds-1" } }))
      .mockResolvedValueOnce(jsonResponse(bigPage))
      .mockResolvedValueOnce(jsonResponse([noCaptionsItem]));

    const urls = Array.from({ length: 1001 }, (_, i) => `video-${i}`);
    const items = await client().getTranscripts(urls);

    expect(items).toHaveLength(1001);
    const datasetCalls = fetchMock.mock.calls.map((c) => String(c[0])).filter((u) => u.includes("/datasets/"));
    expect(datasetCalls[0]).toContain("offset=0");
    expect(datasetCalls[1]).toContain("offset=1000");
  });

  it("throws when the run fails", async () => {
    const urls = Array.from({ length: 60 }, (_, i) => `video-${i}`);
    fetchMock
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-1", status: "READY", defaultDatasetId: "ds-1" } }))
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-1", status: "FAILED", defaultDatasetId: "ds-1" } }));

    await expect(client().getTranscripts(urls)).rejects.toThrow(/status FAILED/);
  });

  it("rejects an empty batch", async () => {
    await expect(client().getTranscripts([])).rejects.toThrow(FetchworksError);
  });
});

describe("getChannelTranscripts", () => {
  it("goes async by default (actor default of 100 videos exceeds the sync limit)", async () => {
    fetchMock
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-2", status: "READY", defaultDatasetId: "ds-2" } }))
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-2", status: "SUCCEEDED", defaultDatasetId: "ds-2" } }))
      .mockResolvedValueOnce(jsonResponse([okItem]));

    await client().getChannelTranscripts("@3blue1brown");

    expect(String(fetchMock.mock.calls[0]![0])).toContain("/runs?");
    expect(JSON.parse(fetchMock.mock.calls[0]![1].body)).toEqual({ channelUrls: ["@3blue1brown"] });
  });

  it("uses the sync endpoint when maxVideosPerChannel is small", async () => {
    fetchMock.mockResolvedValueOnce(jsonResponse([okItem]));

    await client().getChannelTranscripts("@3blue1brown", { maxVideosPerChannel: 10, translateTo: "es" });

    expect(String(fetchMock.mock.calls[0]![0])).toContain("run-sync-get-dataset-items");
    expect(JSON.parse(fetchMock.mock.calls[0]![1].body)).toEqual({
      channelUrls: ["@3blue1brown"],
      maxVideosPerChannel: 10,
      translateTo: "es",
    });
  });
});

describe("getPlaylistTranscripts", () => {
  it("always runs async (playlist size is unknown)", async () => {
    fetchMock
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-3", status: "READY", defaultDatasetId: "ds-3" } }))
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-3", status: "SUCCEEDED", defaultDatasetId: "ds-3" } }))
      .mockResolvedValueOnce(jsonResponse([okItem]));

    await client().getPlaylistTranscripts("PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr");

    expect(String(fetchMock.mock.calls[0]![0])).toContain("/runs?");
    expect(JSON.parse(fetchMock.mock.calls[0]![1].body)).toEqual({
      playlistUrls: ["PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr"],
    });
  });
});

describe("search", () => {
  it("uses the sync endpoint with the actor default of 50 results", async () => {
    fetchMock.mockResolvedValueOnce(jsonResponse([okItem]));

    await client().search("neural networks explained");

    expect(String(fetchMock.mock.calls[0]![0])).toContain("run-sync-get-dataset-items");
    expect(JSON.parse(fetchMock.mock.calls[0]![1].body)).toEqual({
      searchQueries: ["neural networks explained"],
    });
  });

  it("goes async when maxSearchResults reaches the sync limit", async () => {
    fetchMock
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-4", status: "READY", defaultDatasetId: "ds-4" } }))
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-4", status: "SUCCEEDED", defaultDatasetId: "ds-4" } }))
      .mockResolvedValueOnce(jsonResponse([okItem]));

    await client().search("neural networks explained", { maxSearchResults: 200 });

    expect(String(fetchMock.mock.calls[0]![0])).toContain("/runs?");
    expect(JSON.parse(fetchMock.mock.calls[0]![1].body)).toEqual({
      searchQueries: ["neural networks explained"],
      maxSearchResults: 200,
    });
  });
});

describe("polling timeout", () => {
  it("gives up after maxWaitMs", async () => {
    const urls = Array.from({ length: 60 }, (_, i) => `video-${i}`);
    fetchMock
      .mockResolvedValueOnce(jsonResponse({ data: { id: "run-5", status: "READY", defaultDatasetId: "ds-5" } }))
      .mockImplementation(async () =>
        jsonResponse({ data: { id: "run-5", status: "RUNNING", defaultDatasetId: "ds-5" } }),
      );

    await expect(client({ maxWaitMs: 5, pollIntervalMs: 1 }).getTranscripts(urls)).rejects.toThrow(/timed out/);
  });
});
