/** Per-video outcome reported by the actor. Only `ok` items are billed as transcripts. */
export type TranscriptStatus =
  | "ok"
  | "no_captions"
  | "blocked"
  | "live_stream"
  | "age_restricted"
  | "unavailable"
  | "translation_unavailable"
  | "po_token_required"
  | "error";

export type OutputFormat = "segments" | "text" | "srt" | "vtt";

/** A caption track available on the video. */
export interface AvailableLanguage {
  languageCode: string;
  /** "manual" (creator-uploaded) or "asr" (auto-generated). */
  kind: "manual" | "asr";
  name?: string;
  isTranslatable?: boolean;
}

/** One timestamped transcript segment. */
export interface TranscriptSegment {
  /** Start time in seconds. */
  start: number;
  /** Duration in seconds. */
  dur: number;
  text: string;
}

/** Video metadata, included when `includeMetadata` is true (the default). */
export interface VideoMetadata {
  title?: string;
  author?: string;
  channelId?: string;
  lengthSeconds?: number;
  viewCount?: number;
  publishDate?: string;
  category?: string;
  [key: string]: unknown;
}

/** One dataset item per video, exactly as the actor emits it. */
export interface TranscriptItem {
  videoId: string;
  url: string;
  status: TranscriptStatus;
  /** Actual language of the returned track (may differ from the requested priority list). */
  language?: string;
  isAutoGenerated?: boolean;
  availableLanguages?: AvailableLanguage[];
  /** Present when "segments" is in outputFormats and status is "ok". */
  segments?: TranscriptSegment[];
  /** Present when "text" is in outputFormats and status is "ok". */
  text?: string;
  /** Present when "srt" is in outputFormats and status is "ok". */
  srt?: string;
  /** Present when "vtt" is in outputFormats and status is "ok". */
  vtt?: string;
  metadata?: VideoMetadata;
  /** Human-readable reason for non-ok statuses. */
  error?: string;
  [key: string]: unknown;
}

/** Options shared by every method; mirrors the actor input. */
export interface TranscriptOptions {
  /** Language priority list (ISO codes, e.g. ["en", "de"]). First available track wins. Default ["en"]. */
  languages?: string[];
  /** Prefer auto-generated (ASR) tracks over manual captions. Default false. */
  preferAutoGenerated?: boolean;
  /** Target language for YouTube caption auto-translation (best-effort). */
  translateTo?: string;
  /** Transcript representations to include on each item. Default ["segments", "text"]. */
  outputFormats?: OutputFormat[];
  /** Include title, channel, duration, views, publish date, etc. Default true. */
  includeMetadata?: boolean;
  /** Include video chapters (one extra request per video). Default false. */
  includeChapters?: boolean;
}

export interface ChannelOptions extends TranscriptOptions {
  /** Upper bound on videos taken from the channel, newest first. Actor default 100. */
  maxVideosPerChannel?: number;
}

export interface SearchOptions extends TranscriptOptions {
  /** Upper bound on videos taken from the search query. Actor default 50. */
  maxSearchResults?: number;
}

/** Raw actor input, for advanced use. */
export interface ActorInput extends TranscriptOptions {
  videoUrls?: string[];
  channelUrls?: string[];
  maxVideosPerChannel?: number;
  playlistUrls?: string[];
  searchQueries?: string[];
  maxSearchResults?: number;
}

export interface FetchworksClientOptions {
  /** Your Apify API token (https://console.apify.com/settings/integrations). */
  apifyToken: string;
  /** Override the Apify API base URL. Default "https://api.apify.com". */
  baseUrl?: string;
  /** Poll interval for async runs, in ms. Default 3000. */
  pollIntervalMs?: number;
  /** Give up waiting for an async run after this long, in ms. Default 30 minutes. */
  maxWaitMs?: number;
}
